### ISSUE TITLE
Wallet API Fix: Update cancelled transactions status 

### ISSUE THREAD

**Issue by blacktyger** [EpicCash/epic-wallet#19] opened 2022-03-30 12:44 UTC
Allen:
`That’s why I said the v3 wallet could have a mismatched “confirmed” state for some txs that are cancelled when they are just going to become confirmed. The consequence is the tx is cancelled, but the tx state is not changed back to unconfirmed.`

- we need to fix 'confirm' feedback after cancelation of transaction in API calls and `txs` command

**Comment by johanneshahn** [comment] 2022-04-01 06:11
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Required data**
 - Node/Wallet/Miner log as text or screenshot
 - Config toml file or command line 
 - OS: [e.g. Windows]
 - Rust Version
 - Cargo Version

**Additional context**
Add any other context about the problem here.

**Comment by JualnSilva** [comment] 2022-06-30 21:32
Searching the group I found the [entire conversation](https://t.me/c/1679402521/4869) and tried to reproduce it on Usernet:

I tried to perform the following steps described by Allen:

Allen: `A confirmed tx cannot be cancelled. But you can cancel a tx before it becomes “confirmed”. So normally these txs will have “confirmed”: false. However I got several canceled tx (with txtype TxReceivedCancelled) have confirmed tag, which is abnormal I think.`

In my environment, the transactions of both Receiver_Wallet and Sender_Wallet had the field `confirmed?` = false, I will try to run some more variations of this test tomorrow and if I have any progress I will try a correction.

**Comment by JualnSilva** [comment] 2022-07-08 14:23
# Attempts to reproduce the bug

**I was unable to reproduce the error in any of the cases mentioned.**

I have tried to reproduce this error on Usernet in various ways, I have tried to run all tests manually and have not been successful in reproducing the error.

To be more accurate and make sure I didn't miss any points, I generated automated tests to execute the commands for me at the exact time I wanted. I have not been successful in reproducing this error.

In addition, at the end, I did a manual and forced test, I changed the code to wait a few seconds between the execution of the `cancel` command and the actual cancellation of the transaction by the code. Thus being able to cancel the transaction during the confirmation of the same. or shortly before or after too. Even in this case where I forced the wallet code to wait a few seconds, I could not reproduce this error.

# Variations in tests

I basically tried doing the following variations manually and automatically:

Miner (2 possibilities):
- On from the start of the test;
- Off during test. Where it only started at the end of the attempt to confirm the transaction.

Method (3 possibilities):
- http. I only used it with two wallets;
- filet. I used it with two wallets and with only one, the one I sent was the same one I received;
- self. In this method, I only used the wallet you sent.

Wallets (2 possibilities):
- Only Sender, where it sent and received the transaction itself;
- Sender and Receiver. in cases where I had transactions by http and file methods.

Cancellation options (3 possibilities):
- Cancel only the transaction sent;
In this case, the fee for executing the `send` command is debited from the coins but the transaction does not finish. In no case, I have seen.

- Cancel only the transaction received;
The transaction takes place normally, the money is debited from the wallet you sent and goes to the wallet you received.

The original transaction received is `Received tx - Canceled` and with status `Confirmed = false` and the money moved appears in the history in the form of another line, that is, it is as if I had received a "new" output.

- Cancel both transactions.


Command order (4 possibilities):

We have the only command that is manual `cancel`. Confirmation happens automatically when the miner finds more blocks and sends them to the chain.

- Execute the `cancel` command before committing the transaction
In this case, the transaction that was in the pool is removed from there as soon as the first block is generated after this cancellation. The transaction is not confirmed.

- Execute the `cancel` command after committing the transaction
In this case, the system shows an error that makes it impossible to cancel because the transaction is already confirmed.

You can see this verification in the following command line inside the cancel function on file `/epic-wallet/libwallet/src/internal/tx.rs` :

```rust
if tx.tx_type != TxLogEntryType::TxSent && tx.tx_type != TxLogEntryType::TxReceived {
		return Err(ErrorKind::TransactionNotCancellable(tx_id_string))?;
	}
	if tx.confirmed == true {
		return Err(ErrorKind::TransactionNotCancellable(tx_id_string))?;
	}
```

- Execute `cancel` command during the confirmation
To do this I needed to make that change I mentioned at the beginning where I changed the code to wait a few seconds trying to make the block confirm my transaction during the cancellation process.

Trying to force the transaction to have the status of `confirmed = true` and at the end also have the message that the transaction was canceled.

However, in this case, either the miner was stopped without being able to send the block to the chain because the transaction was canceled shortly before he was able to confirm it.

Or the transaction was done normally and the cancellation returned the error that it was impossible to cancel a committed transaction.

# Combination of scenarios

The possible combinations of scenarios are the ones I mentioned above, however the Method depends on the amount of wallets I'm going to use and vice versa.

So if I used the `self` method, I would have to use only 1 wallet.

With the method being `http` I only used it with two wallets.

The `file` method was where I tested with one and two wallets.

Resulting in 4 possibilities for Method x Wallets.

So we have:

2 - Miner;
4 - Method x Wallets;
3 - Cancellation options;
4 - Command order.

resulting in 2*4*3*4 = **96 scenarios** tested. Manually and automatically.

# Conclusion

With all these scenarios tested and the code investigation done. We came to the conclusion that it is very difficult to reproduce this error.

With all this evidence I'm assuming this is a very unlikely error to happen. In addition to appearing to be just a visual error from what was reported on Telegram.

For these statements made, I will close this bug and in case anyone manages to reproduce or has evidence that it is something more serious than what I mentioned, I ask you to open it and demonstrate that you have such information.

**Closed by JualnSilva** 2022-07-08 14:23 UTC
Labels: question
